# Generated by Django 2.1.5 on 2020-01-12 12:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_picture', models.FileField(default='blah.jpg', upload_to='')),
                ('email', models.CharField(default='Malcom2000@live.se', max_length=100)),
                ('Liked_or_Not', models.BooleanField(default=False)),
                ('about', models.CharField(max_length=10000)),
                ('subscribers', models.IntegerField(default=0)),
                ('videos', models.CharField(default=0, max_length=100000000)),
                ('Following', models.ManyToManyField(related_name='account', to=settings.AUTH_USER_MODEL)),
                ('subscriptions', models.ManyToManyField(related_name='accountss', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ip_Adresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip_A', models.CharField(max_length=1000000)),
                ('Last_time_watched', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo_Pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='postss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_file', models.FileField(upload_to='')),
                ('descriptions', models.CharField(max_length=1000)),
                ('viewss', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('Text_Button', models.TextField(default='Like', max_length=100000)),
                ('dislikes', models.CharField(max_length=1000000000)),
                ('Thumbnail', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('PostDate', models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 12, 12, 7, 49, 532951))),
                ('Author', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memster', to=settings.AUTH_USER_MODEL)),
                ('Who_like', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True, default='')),
                ('reply_comments', models.TextField(blank=True, default='')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leads.postss')),
            ],
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
