# Generated by Django 2.1.5 on 2020-01-29 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200112_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postss',
            old_name='post_file',
            new_name='Videos_file',
        ),
        migrations.AddField(
            model_name='postss',
            name='Pictures_file',
            field=models.FileField(default='0', upload_to=''),
        ),
        migrations.AlterField(
            model_name='postss',
            name='PostDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 29, 10, 41, 57, 54037)),
        ),
    ]
