# Generated by Django 2.1.5 on 2020-02-08 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20200202_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postss',
            name='Pictures_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='postss',
            name='PostDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 8, 20, 59, 37, 239593)),
        ),
    ]
