# Generated by Django 2.1.5 on 2020-02-12 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20200208_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postss',
            name='Pictures_file',
            field=models.ImageField(upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='postss',
            name='PostDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 12, 14, 7, 37, 363543)),
        ),
    ]
