# Generated by Django 2.1.5 on 2020-05-20 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20200212_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postss',
            name='Pictures_file',
            field=models.FileField(upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='postss',
            name='PostDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 20, 21, 9, 3, 944965)),
        ),
    ]
