# Generated by Django 2.1.5 on 2020-05-20 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20200520_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='postss',
            name='GIFS_String',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='postss',
            name='Pictures_file',
            field=models.FileField(blank=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='postss',
            name='PostDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 20, 21, 37, 33, 64372)),
        ),
    ]
