# Generated by Django 2.1.5 on 2020-05-20 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20200520_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postss',
            name='PostDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 20, 23, 15, 19, 109577)),
        ),
    ]
